language: java

jdk:
  - oraclejdk8
  
branches:
  only:
    - master
    - develop
    
notifications:
  email:
    recipients:
      - javier.reyes.mangas@alumnos.upm.es
    webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
script: mvn verify